# locals {
#   common = yamldecode(file("../common.yaml"))
# }

# module "synthetics" {
#   source = "../../../modules/synthetics"

#   env           = local.common.env
#   network_envs  = local.common.network_envs
#   notification  = local.common.notification
#   enable_checks = true

#   enable_simple_browser_checks = true

#   checks_info = {
#     /* 1 = {
#       enabled      = local.common.enabled
#       url          = "https://ncar.infocert.it/regws/services/RegistrazioneAnagraficaWS?wsdl"
#       url_num      = 1
#       label        = "RegistrazioneAnagraficaWS"
#       service_name = "DORegistrazioneAnagraficaService"
#       product      = "NCAR"
#       tech_serv    = "ST Registration Authority"
#       script       = "wsdl_check_script.tpl"
#       user         = ""
#       pass         = ""
#       freq         = 10
#       priv_loc     = false
#       multi_loc    = true
#       duration_thr = 2000
#       result_thr   = 1200
#       max_failures = 2
#     } */
#     # 16 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncar.infocert.it/ncar/"
#     #   url_num      = 1
#     #   label        = "FrontEnd Login"
#     #   service_name = ""
#     #   product      = "NCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   script       = "nav_NCAR_login.tpl"
#     #   user         = "NCAR_LOGIN_USER_PRD"
#     #   pass         = "NCAR_LOGIN_PASS_PRD"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   duration_thr = 8000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     /* 17 = {
#       enabled      = local.common.enabled
#       url          = "https://ncar.infocert.it/pcarweb/default.do"
#       url_num      = 1
#       label        = "Prenotazione Registrazione"
#       service_name = ""
#       product      = "NCAR"
#       tech_serv    = "ST Registration Authority"
#       script       = "nav_NCAR_PrenotaRegistrazione.tpl"
#       user         = ""
#       pass         = ""
#       freq         = 10
#       multi_loc    = true
#       priv_loc     = false
#       duration_thr = 2000
#       result_thr   = 1200
#       max_failures = 2
#     } */
#     # 28 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://marte.infocert.it/cdie/wtest.html"
#     #   url_num      = 1
#     #   label        = "Marcatura"
#     #   service_name = ""
#     #   product      = "MARTE"
#     #   tech_serv    = "ST Marcatura Temporale"
#     #   script       = "nav_MARTE_marcatura_selenium4.tpl"
#     #   user         = "MARTE_MARC_USER_PRD"
#     #   pass         = "MARTE_MARC_PASS_PRD"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   duration_thr = 3000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 29 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://marte.print.infocert.it/cdie/wtest.html"
#     #   url_num      = 1
#     #   label        = "Marcatura Print"
#     #   service_name = ""
#     #   product      = "MARTE"
#     #   tech_serv    = "ST Marcatura Temporale"
#     #   script       = "nav_MARTE_marcatura_selenium4.tpl"
#     #   user         = "MARTE_MARC_USER_PRD"
#     #   pass         = "MARTE_MARC_PASS_PRD"
#     #   freq         = 10
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 3000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 30 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://marte.zucchetti.infocert.it/cdie/wtest.html"
#     #   url_num      = 1
#     #   label        = "Marcatura Zucchetti"
#     #   service_name = ""
#     #   product      = "MARTE"
#     #   tech_serv    = "ST TSA Zucchetti"
#     #   script       = "nav_MARTE_marcatura_selenium4.tpl"
#     #   user         = "MARTE_MARC_ZUC_USER_PRD"
#     #   pass         = "MARTE_MARC_ZUC_PASS_PRD"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   duration_thr = 4000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 31 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://digitaltimestamp.print.infocert.it/idts-rest/dts/welcome"
#     #   url_num      = 1
#     #   label        = "IDTS Welcome Service"
#     #   service_name = "IDTS-REST welcome"
#     #   product      = "IDTS"
#     #   tech_serv    = "ST Marcatura Temporale"
#     #   script       = "nav_GENERAL_pattern.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 10
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     /* 32 = {
#       enabled      = local.common.enabled
#       url          = "https://rest.legalcert.print.infocert.it/lcrs-rest/welcome/"
#       url_num      = 1
#       label        = "Welcome Service"
#       service_name = "Benvenuti in LCRS"
#       product      = "LCRS"
#       tech_serv    = "ST Registration Authority"
#       script       = "nav_GENERAL_pattern.tpl"
#       user         = ""
#       pass         = ""
#       freq         = 10
#       multi_loc    = false
#       priv_loc     = true
#       duration_thr = 2000
#       result_thr   = 1500
#       max_failures = 0
#     } */
#     # 33 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://cabe.print.infocert.it/cabe-webconsole/infos"
#     #   url_num      = 1
#     #   label        = "Welcome Service"
#     #   service_name = "Benvenuti in LCRS"
#     #   product      = "CABE"
#     #   tech_serv    = "ST Registration Authority"
#     #   script       = "nav_CABE_login_selenium4.tpl"
#     #   user         = "CABE_LOGIN_USER_PRD"
#     #   pass         = "CABE_LOGIN_PASS_PRD"
#     #   freq         = 10
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 4000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 34 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ecer.infocert.it/ecer-webservice/"
#     #   url_num      = 1
#     #   label        = "Welcome Service"
#     #   service_name = "Hello World!"
#     #   product      = "ECER"
#     #   tech_serv    = "ST Generazione Altri Certificati"
#     #   script       = "nav_GENERAL_pattern.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 35 = {
#     #   enabled      = false
#     #   url          = "http://ocsp.infocert.it/OCSPServer_ICE/OCSPServlet"
#     #   url_num      = 1
#     #   label        = "Welcome Service"
#     #   service_name = "Welcome to the Axway Validation Authority Server"
#     #   product      = "OCSP"
#     #   tech_serv    = "ST Verifica Revoche"
#     #   script       = "nav_GENERAL_pattern.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     36 = {
#       // TODO temp rilascio nuovo sito firma
#       enabled      = false
#       url          = "https://www.firma.infocert.it/utenti/"
#       url_num      = 1
#       label        = "Registration Authority"
#       service_name = ""
#       product      = "SOSPENSIONE"
#       tech_serv    = "ST Registration Authority"
#       script       = "nav_SOSPENSIONE.tpl"
#       user         = ""
#       pass         = ""
#       freq         = 10
#       multi_loc    = true
#       priv_loc     = false
#       duration_thr = 10000
#       result_thr   = 1200
#       max_failures = 2
#     }
#     # 44 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://sere.print.infocert.it/sere-rest/sere-admin/welcome"
#     #   url_num      = 1
#     #   label        = "Welcome"
#     #   service_name = "WELCOME"
#     #   product      = "SERE"
#     #   tech_serv    = "ST Registration Authority"
#     #   script       = "nav_GENERAL_pattern.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 10
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 46 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://mysign.infocert.it/#/login"
#     #   url_num      = 1
#     #   label        = "Login MySign"
#     #   service_name = "MySign"
#     #   product      = "MySign"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   script       = "nav_MYSIGN_login.tpl"
#     #   user         = "MYSIGN_LOGIN_USER_PRD"
#     #   pass         = "MYSIGN_LOGIN_PASS_PRD"
#     #   freq         = 5
#     #   priv_loc     = false
#     #   multi_loc    = false
#     #   duration_thr = 8000
#     #   result_thr   = 1500
#     #   max_failures = 2
#     # }
#     /* 47 = {
#       enabled      = local.common.enabled
#       url          = "https://lcrsisp.infocert.it/lcrs-service/welcome/"
#       url_num      = 1
#       label        = "Welcome Service"
#       service_name = "Benvenuti in LCRS"
#       product      = "LCRS ISP"
#       tech_serv    = "ST Registration Authority"
#       script       = "nav_GENERAL_pattern.tpl"
#       user         = ""
#       pass         = ""
#       freq         = 10
#       multi_loc    = true
#       priv_loc     = false
#       duration_thr = 2000
#       result_thr   = 1200
#       max_failures = 2
#     } */
#     /* 49 = {
#       enabled      = local.common.enabled
#       url          = "https://ncarisp.infocert.it/regws/services/RegistrazioneAnagraficaWS?wsdl"
#       url_num      = 1
#       label        = "RegistrazioneAnagraficaWS"
#       service_name = "DORegistrazioneAnagraficaService"
#       product      = "NCAR ISP"
#       tech_serv    = "ST Registration Authority"
#       script       = "wsdl_check_script.tpl"
#       user         = ""
#       pass         = ""
#       freq         = 10
#       multi_loc    = true
#       priv_loc     = false
#       duration_thr = 2000
#       result_thr   = 1200
#       max_failures = 2
#     } */
#     # 54 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://supernova.print.infocert.it/login?redirect=%2Fhome"
#     #   url_num      = 1
#     #   label        = "Login Supernova"
#     #   service_name = "mo604564"
#     #   product      = "SUPERNOVA"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   script       = "nav_SUPERNOVA_templates_selenium4.tpl"
#     #   user         = "SUPERNOVA_LOGIN_USER_PRD"
#     #   pass         = "SUPERNOVA_LOGIN_PASS_PRD"
#     #   freq         = 10
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 10000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#   }

#   API_checks_info = {
#     # 1 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/FirmaFR"
#     #   url_num      = 1
#     #   label        = "FirmaCADES"
#     #   service_name = "Operazione terminata con successo"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   script       = "NCFR_firma_CADES.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   priv_loc     = false
#     #   multi_loc    = true
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 2 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://pulce.print.infocert.it/pulce/welcome"
#     #   url_num      = 1
#     #   label        = "Welcome"
#     #   service_name = "no Authorization header found"
#     #   product      = "PULCE"
#     #   tech_serv    = "ST Registration Authority"
#     #   script       = "PULCE_welcome.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   priv_loc     = true
#     #   multi_loc    = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 3 = {
#     #   enabled      = false
#     #   url          = "https://pulsar.eu-west-1.praws.infocert.it/v0/bind"
#     #   url_num      = 1
#     #   label        = "Bind"
#     #   service_name = ""
#     #   product      = "PULSAR"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   script       = "PULSAR_Bind.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   priv_loc     = true
#     #   multi_loc    = false
#     #   duration_thr = 3000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 4 = {
#     #   enabled      = false
#     #   url          = "https://pulsar.eu-west-1.praws.infocert.it/v0/verify"
#     #   url_num      = 1
#     #   label        = "Verify"
#     #   service_name = ""
#     #   product      = "PULSAR"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   script       = "PULSAR_Verify.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   priv_loc     = true
#     #   multi_loc    = false
#     #   duration_thr = 3000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 5 = {
#     #   enabled      = false
#     #   url          = "https://pulsar.eu-west-1.praws.infocert.it/v0/resend"
#     #   url_num      = 1
#     #   label        = "Resend"
#     #   service_name = ""
#     #   product      = "PULSAR"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   script       = "PULSAR_Resend.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   priv_loc     = true
#     #   multi_loc    = false
#     #   duration_thr = 10000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 6 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://pulsarpr.eu-west-1.praws.infocert.it/pr_regaut2/bind"
#     #   url_num      = 2
#     #   label        = "Bind"
#     #   service_name = ""
#     #   product      = "PULSAR"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   script       = "PULSAR_Bind.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   priv_loc     = true
#     #   multi_loc    = false
#     #   duration_thr = 5000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 7 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://pulsarpr.eu-west-1.praws.infocert.it/pr_regaut2/verify"
#     #   url_num      = 2
#     #   label        = "Verify"
#     #   service_name = ""
#     #   product      = "PULSAR"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   script       = "PULSAR_Verify.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   priv_loc     = true
#     #   multi_loc    = false
#     #   duration_thr = 5000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 8 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://pulsarpr.eu-west-1.praws.infocert.it/pr_regaut2/resend"
#     #   url_num      = 2
#     #   label        = "Resend"
#     #   service_name = ""
#     #   product      = "PULSAR"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   script       = "PULSAR_Resend.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   priv_loc     = true
#     #   multi_loc    = false
#     #   duration_thr = 10000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#   }

#   SIMPLE_BROWSER_checks_info = {
#     /* 4 = {
#       enabled      = local.common.enabled
#       url          = "https://shield.infocert.it/actuator/health/ready"
#       url_num      = 1
#       label        = "Health Check - printbc"
#       pattern      = "\"status\":\"UP\","
#       product      = "SHIELD"
#       tech_serv    = "ST TRISS SSA"
#       priv_loc     = false
#       duration_thr = 2000
#       result_thr   = 1200
#       max_failures = 2
#     } */
#     # 5 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://roll.infocert.it/actuator/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   pattern      = "\"status\":\"UP\","
#     #   product      = "ROLL"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   priv_loc     = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 6 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://jimmy.printbc.infocert.it/actuator/health"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   pattern      = "\"status\":\"UP\","
#     #   product      = "JIMMY"
#     #   tech_serv    = "ST TRISS SSA"
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     /* 7 = {
#       enabled      = local.common.enabled
#       url          = "https://shieldq.printbc.infocert.it/actuator/health/ready"
#       url_num      = 1
#       label        = "Health Check - printbc"
#       pattern      = "\"status\":\"UP\","
#       product      = "SHIELDQ"
#       tech_serv    = "ST TRISSQ"
#       priv_loc     = true
#       duration_thr = 2000
#       result_thr   = 1200
#       max_failures = 2
#     } */
#     # 8 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://rollq.printbc.infocert.it/actuator/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   pattern      = "\"status\":\"UP\","
#     #   product      = "ROLLQ"
#     #   tech_serv    = "ST TRISSQ"
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 9 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://jimmyq.printbc.infocert.it/actuator/health"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   pattern      = "\"status\":\"UP\","
#     #   product      = "JIMMYQ"
#     #   tech_serv    = "ST TRISSQ"
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     #7 = {
#     #  enabled      = local.common.enabled
#     #  url          = "https://nasa.printbc.infocert.it/health/ready"
#     #  url_num      = 1
#     #  label        = "Health Check - printbc"
#     #  pattern      = "\"status\": \"UP\","
#     #  product      = "NASA"
#     #  tech_serv    = "ST Verifica Revoche"
#     #  priv_loc     = true
#     #  duration_thr = 2000
#     #  result_thr   = 1800
#     #  max_failures = 2
#     #}
#   }

#   SIMPLE_BROWSER_CA_checks_info = {
#     /* 1 = {
#       enabled      = local.common.enabled
#       url          = "https://parsec.prdmzbc.ca.infocert.it/health/ready"
#       url_num      = 1
#       label        = "Health Check - prdmzbc.ca"
#       pattern      = "\"status\": \"UP\","
#       product      = "PARSEC"
#       tech_serv    = "ST Registration Authority 2"
#       priv_loc     = true
#       duration_thr = 2000
#       result_thr   = 1500
#       max_failures = 0
#     } */
#     /* 2 = {
#       enabled      = local.common.enabled
#       url          = "https://crypto.printbc.ca.infocert.it/health/ready"
#       url_num      = 1
#       label        = "Health Check - prdmzbc.ca"
#       pattern      = "\"status\": \"UP\","
#       product      = "CRYPTO"
#       tech_serv    = "ST TRISS"
#       priv_loc     = true
#       duration_thr = 2000
#       result_thr   = 1500
#       max_failures = 0
#     } */
#     # 3 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://triss.printbc.ca.infocert.it/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - prdmzbc.ca"
#     #   pattern      = "\"status\": \"UP\","
#     #   product      = "TRISS"
#     #   tech_serv    = "ST TRISS"
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     /*4 = {
#       enabled      = local.common.enabled
#       url          = "https://deck.prdmzbc.ca.infocert.it/health/ready"
#       url_num      = 1
#       label        = "Health Check - prdmzbc.ca"
#       pattern      = "\"status\": \"UP\","
#       product      = "DECK"
#       tech_serv    = "ST TRISSQ"
#       priv_loc     = true
#       duration_thr = 2000
#       result_thr   = 1500
#       max_failures = 0
#     }*/
#   }

#   checks_info_once_day = {
#     # 1 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://ip1pvliasblc002.print.infocert.it:8081/api/probe/lei-job/last-execution"
#     #   url_num      = 1
#     #   label        = "LEI"
#     #   service_name = "LEI"
#     #   product      = "LCER JOB"
#     #   tech_serv    = "LCER JOB"
#     #   script       = "nav_JOB_scriptedAPI.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 1440
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 2 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://ip1pvliasblc002.print.infocert.it:8081/api/probe/notify-db-job/last-execution"
#     #   url_num      = 1
#     #   label        = "NOTIFY DB"
#     #   service_name = "NOTIFY DB"
#     #   product      = "LCER JOB"
#     #   tech_serv    = "LCER JOB"
#     #   script       = "nav_JOB_scriptedAPI.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 1440
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 3 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://ip1pvliasblc002.print.infocert.it:8081/api/probe/log-pkbox-job/last-execution"
#     #   url_num      = 1
#     #   label        = "LOG PKBOX"
#     #   service_name = "LOG PKBOX"
#     #   product      = "LCER JOB"
#     #   tech_serv    = "LCER JOB"
#     #   script       = "nav_JOB_scriptedAPI.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 1440
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#   }

#   ping_monitors = {
#     # 1 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcar.infocert.it/CustomerCertEmitterWS/emitterCertRequest.wsdl"
#     #   url_num      = 1
#     #   label        = "CustomerCertEmitterWS"
#     #   service_name = "EmitterCertRequestService"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 2 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcar.infocert.it/infora-webservice/RegistrationBaseAut?wsdl"
#     #   url_num      = 1
#     #   label        = "RegistrationBaseAut"
#     #   service_name = "RegistrationBaseAutService"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 3 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcar.infocert.it/infora-webservice/RegistrationHandleWS?wsdl"
#     #   url_num      = 1
#     #   label        = "RegistrationHandleWS"
#     #   service_name = "RegistrationHandleWSService"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 4 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcar.infocert.it/infora-webservice/RegistrationWS?wsdl"
#     #   url_num      = 1
#     #   label        = "RegistrationWS"
#     #   service_name = "RegistrationWSService"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 5 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcar.infocert.it/AttCertFirma/WsAccContratti?wsdl"
#     #   url_num      = 1
#     #   label        = "WsAccContratti"
#     #   service_name = "WsAccContratti"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 6 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcar.infocert.it/AttCertFirma/WsAttCerts?wsdl"
#     #   url_num      = 1
#     #   label        = "WsAttCerts"
#     #   service_name = "WsAttivazioneCerts"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 7 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcar.infocert.it/AttCertFirma/WsVerXML?wsdl"
#     #   url_num      = 1
#     #   label        = "WsVerXML"
#     #   service_name = "WsVerificaXML"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 8 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcar.infocert.it/ERCWebService/ERCNServiceWS?wsdl"
#     #   url_num      = 1
#     #   label        = "ERCNServiceWS"
#     #   service_name = "ERCServiceFRService"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 9 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcarisp.infocert.it/infora-webservice/RegistrationBaseAut?wsdl"
#     #   url_num      = 1
#     #   label        = "RegistrationBaseAut"
#     #   service_name = "RegistrationBaseAut"
#     #   product      = "WCAR ISP"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 10 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://icss.infocert.it/icss-rest/welcome/"
#     #   url_num      = 1
#     #   label        = "Welcome"
#     #   service_name = "Welcome to ICSS server"
#     #   product      = "ICSS"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 11 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://icss.print.infocert.it/icss-intra-rest/welcome/"
#     #   url_num      = 1
#     #   label        = "Welcome intra"
#     #   service_name = "Welcome to ICSS server"
#     #   product      = "ICSS"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 12 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://icss.print.infocert.it/icss-intra-rest/probe/"
#     #   url_num      = 1
#     #   label        = "Probe intra"
#     #   service_name = "ICSS seems to be working properly"
#     #   product      = "ICSS"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 13 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://vlijbsignice001.print.infocert.it:8080/icss-intra-rest/probe"
#     #   url_num      = 1
#     #   label        = "vlijbsignice001"
#     #   service_name = "ICSS seems to be working properly"
#     #   product      = "ICSS"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 14 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://vlijbsignice002.print.infocert.it:8080/icss-intra-rest/probe"
#     #   url_num      = 1
#     #   label        = "vlijbsignice002"
#     #   service_name = "ICSS seems to be working properly"
#     #   product      = "ICSS"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 15 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://vlijbsignice003.print.infocert.it:8080/icss-intra-rest/probe"
#     #   url_num      = 1
#     #   label        = "vlijbsignice003"
#     #   service_name = "ICSS seems to be working properly"
#     #   product      = "ICSS"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 16 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://vlijbsignice004.print.infocert.it:8080/icss-intra-rest/probe"
#     #   url_num      = 1
#     #   label        = "vlijbsignice004"
#     #   service_name = "ICSS seems to be working properly"
#     #   product      = "ICSS"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 17 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://vlijbsignice005.print.infocert.it:8080/icss-intra-rest/probe"
#     #   url_num      = 1
#     #   label        = "vlijbsignice005"
#     #   service_name = "ICSS seems to be working properly"
#     #   product      = "ICSS"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 18 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://vlijbsignice006.print.infocert.it:8080/icss-intra-rest/probe"
#     #   url_num      = 1
#     #   label        = "vlijbsignice006"
#     #   service_name = "ICSS seems to be working properly"
#     #   product      = "ICSS"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 19 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://nova.printbc.infocert.it/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   service_name = "\"status\": \"UP\","
#     #   product      = "NOVA"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 20 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://nebula.printbc.infocert.it/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   service_name = "\"status\": \"UP\","
#     #   product      = "NEBULA"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 21 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wormhole.printbc.infocert.it/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   service_name = "\"status\": \"UP\","
#     #   product      = "WORMHOLE"
#     #   tech_serv    = "ST PKI INTESA FD 2"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 22 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/FirmaFR?wsdl"
#     #   url_num      = 1
#     #   label        = "FirmaFR"
#     #   service_name = "FirmaFR"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 23 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/FirmaWS?wsdl"
#     #   url_num      = 1
#     #   label        = "FirmaWS"
#     #   service_name = "firmaWSService"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 24 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/GenCertFR?wsdl"
#     #   url_num      = 1
#     #   label        = "GenCertFR"
#     #   service_name = "GenCertFR"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 25 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/GenCertMedWS?wsdl"
#     #   url_num      = 1
#     #   label        = "GenCertMedWS"
#     #   service_name = "GenCertMedService"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 26 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/RegCertFR?wsdl"
#     #   url_num      = 1
#     #   label        = "RegCertFR"
#     #   service_name = "RegCertFR"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 27 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/ManagerCredWS?wsdl"
#     #   url_num      = 1
#     #   label        = "ManagerCredWS"
#     #   service_name = "ManagerCredWSService"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 28 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/RegCertMedWS?wsdl"
#     #   url_num      = 1
#     #   label        = "RegCertMedWS"
#     #   service_name = "RegCertMed"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 29 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/OTPSender?wsdl"
#     #   url_num      = 1
#     #   label        = "OTPSender"
#     #   service_name = "OTPSenderWSService"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 30 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/PKBoxManager?wsdl"
#     #   url_num      = 1
#     #   label        = "PKBoxManager"
#     #   service_name = "GenerateCertificatePKBoxService"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 31 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfr.infocert.it/ncfr-webservice/ServerMaRe?wsdl"
#     #   url_num      = 1
#     #   label        = "ServerMaRe"
#     #   service_name = "ServerMaRe"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 32 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ip1pvliwsfir001.print.infocert.it:50443/ncfr-webservice/FirmaFR?wsdl"
#     #   url_num      = 1
#     #   label        = "FirmaFR - Apache instance 001"
#     #   service_name = "FirmaFR"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 3000
#     #   result_thr   = 1500
#     #   max_failures = 2
#     # }
#     # 33 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ip1pvliwsfir002.print.infocert.it:50443/ncfr-webservice/FirmaFR?wsdl"
#     #   url_num      = 1
#     #   label        = "FirmaFR - Apache instance 002"
#     #   service_name = "FirmaFR"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 3000
#     #   result_thr   = 1500
#     #   max_failures = 2
#     # }
#     # 34 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ip1pvliwsfir003.print.infocert.it:50443/ncfr-webservice/FirmaFR?wsdl"
#     #   url_num      = 1
#     #   label        = "FirmaFR - Apache instance 003"
#     #   service_name = "FirmaFR"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 3000
#     #   result_thr   = 1500
#     #   max_failures = 2
#     # }
#     # 35 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ip1pvliwsfir004.print.infocert.it:50443/ncfr-webservice/FirmaFR?wsdl"
#     #   url_num      = 1
#     #   label        = "FirmaFR - Apache instance 004"
#     #   service_name = "FirmaFR"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 3000
#     #   result_thr   = 1500
#     #   max_failures = 2
#     # }
#     # 36 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://digitaltimestamp.print.infocert.it/idts-rest/dts/welcome"
#     #   url_num      = 1
#     #   label        = "IDTS Welcome Service"
#     #   service_name = "IDTS-REST welcome"
#     #   product      = "IDTS"
#     #   tech_serv    = "ST Marcatura Temporale"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 37 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://jimmy.printbc.infocert.it/actuator/health"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   service_name = "\"status\":\"UP\","
#     #   product      = "JIMMY"
#     #   tech_serv    = "ST TRISS SSA"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 38 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://jimmyq.printbc.infocert.it/actuator/health"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   service_name = "\"status\":\"UP\","
#     #   product      = "JIMMYQ"
#     #   tech_serv    = "ST TRISSQ"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 39 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://triss.printbc.ca.infocert.it/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - prdmzbc.ca"
#     #   service_name = "\"status\": \"UP\","
#     #   product      = "TRISS"
#     #   tech_serv    = "ST TRISS"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 40 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://roll.infocert.it/actuator/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   service_name = "\"status\":\"UP\","
#     #   product      = "ROLL"
#     #   tech_serv    = "ST InfoCert Sign Server"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 41 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://rollq.printbc.infocert.it/actuator/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   service_name = "\"status\":\"UP\","
#     #   product      = "ROLLQ"
#     #   tech_serv    = "ST TRISSQ"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 42 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://parsec.prdmzbc.ca.infocert.it/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - prdmzbc.ca"
#     #   service_name = "\"status\": \"UP\","
#     #   product      = "PARSEC"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 43 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://crypto.printbc.ca.infocert.it/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - prdmzbc.ca"
#     #   service_name = "\"status\": \"UP\","
#     #   product      = "CRYPTO"
#     #   tech_serv    = "ST TRISS"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
# 	  # 44 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://shield.infocert.it/actuator/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   service_name = "\"status\":\"UP\","
#     #   product      = "SHIELD"
#     #   tech_serv    = "ST TRISS SSA"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 45 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://shieldq.printbc.infocert.it/actuator/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   service_name = "\"status\":\"UP\","
#     #   product      = "SHIELDQ"
#     #   tech_serv    = "ST TRISSQ"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 46 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://nasa.printbc.infocert.it/health/ready"
#     #   url_num      = 1
#     #   label        = "Health Check - printbc"
#     #   service_name = "\"status\": \"UP\","
#     #   product      = "NASA"
#     #   tech_serv    = "ST Verifica Revoche"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1800
#     #   max_failures = 2
#     # }
#     # 47 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://rest.legalcert.print.infocert.it/lcrs-rest/welcome/"
#     #   url_num      = 1
#     #   label        = "Welcome Service"
#     #   service_name = "Benvenuti in LCRS"
#     #   product      = "LCRS"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 48 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://lcrsisp.infocert.it/lcrs-service/welcome/"
#     #   url_num      = 1
#     #   label        = "Welcome Service"
#     #   service_name = "Benvenuti in LCRS"
#     #   product      = "LCRS ISP"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
# 	  # 49 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncar.infocert.it/regws/services/RegistrazioneAnagraficaWS?wsdl"
#     #   url_num      = 1
#     #   label        = "RegistrazioneAnagraficaWS"
#     #   service_name = "DORegistrazioneAnagraficaService"
#     #   product      = "NCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
# 	  # 50 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncar.infocert.it/pcarweb/default.do"
#     #   url_num      = 1
#     #   label        = "Prenotazione Registrazione"
#     #   service_name = "Prenotazione richiesta registrazione"
#     #   product      = "NCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
# 	  # 51 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncarisp.infocert.it/regws/services/RegistrazioneAnagraficaWS?wsdl"
#     #   url_num      = 1
#     #   label        = "RegistrazioneAnagraficaWS"
#     #   service_name = "DORegistrazioneAnagraficaService"
#     #   product      = "NCAR ISP"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 52 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://api.infocert.digital/validation/signature/v2/info"
#     #   url_num      = 1
#     #   label        = "Health Check v2 - praws"
#     #   service_name = "lcert-sigval-vaga"
#     #   product      = "VAGA"
#     #   tech_serv    = "sigval"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 53 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://api.infocert.digital/validation/signature/v3/info"
#     #   url_num      = 1
#     #   label        = "Health Check v3 - praws"
#     #   service_name = "lcert-sigval-vaga"
#     #   product      = "VAGA"
#     #   tech_serv    = "sigval"
#     #   freq         = 5
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 54 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://atumpr.eu-south-1.prawsbc.infocert.it/atum/health"
#     #   url_num      = 1
#     #   label        = "Health Check - praws"
#     #   service_name = "\"status\": \"UP\","
#     #   product      = "ATUM"
#     #   tech_serv    = "ST-ATUM"
#     #   freq         = 5
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 0
#     # }
#   }
# }