# locals {
#   common = yamldecode(file("../common.yaml"))
# }

# module "synthetics" {
#   source = "../../../modules/synthetics"

#   env                          = local.common.env
#   network_envs                 = local.common.network_envs
#   notification                 = local.common.notification
#   enable_checks                = true
#   enable_simple_browser_checks = false
#   checks_info = {
#     /* 1 = {
#       enabled      = local.common.enabled
#       url          = "https://ncarcl.infocert.it/regws/services/RegistrazioneAnagraficaWS?wsdl"
#       url_num      = 1
#       label        = "RegistrazioneAnagraficaWS"
#       service_name = "DORegistrazioneAnagraficaService"
#       product      = "NCAR"
#       tech_serv    = "ST Registration Authority"
#       script       = "wsdl_check_script.tpl"
#       user         = ""
#       pass         = ""
#       freq         = 10
#       multi_loc    = true
#       priv_loc     = false
#       duration_thr = 2000
#       result_thr   = 1200
#       max_failures = 2
#     } */
#     # 10 = {
#     #   // TODO temp relase NCAR
#     #   enabled      = false
#     #   url          = "https://ncarcl.infocert.it/ncar/"
#     #   url_num      = 1
#     #   label        = "FrontEnd Login"
#     #   service_name = ""
#     #   product      = "NCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   script       = "nav_NCAR_login_cl.tpl"
#     #   user         = "NCAR_LOGIN_USER_COL"
#     #   pass         = "NCAR_LOGIN_PASS_COL"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   duration_thr = 8000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     /* 11 = {
#       enabled      = local.common.enabled
#       url          = "https://ncarcl.infocert.it/pcarweb/default.do"
#       url_num      = 1
#       label        = "Prenotazione Registrazione"
#       service_name = ""
#       product      = "NCAR"
#       tech_serv    = "ST Registration Authority"
#       script       = "nav_NCAR_PrenotaRegistrazione.tpl"
#       user         = ""
#       pass         = ""
#       freq         = 10
#       multi_loc    = true
#       priv_loc     = false
#       duration_thr = 2000
#       result_thr   = 1200
#       max_failures = 2
#     } */
#     /* 22 = {
#       enabled      = local.common.enabled
#       url          = "https://restcl.legalcert.infocert.it/lcrs-service/welcome/"
#       url_num      = 1
#       label        = "Welcome Service"
#       service_name = "Benvenuti in LCRS"
#       product      = "LCRS"
#       tech_serv    = "ST Registration Authority"
#       script       = "nav_GENERAL_pattern.tpl"
#       user         = ""
#       pass         = ""
#       freq         = 10
#       multi_loc    = true
#       priv_loc     = false
#       duration_thr = 2000
#       result_thr   = 1200
#       max_failures = 2
#     } */
#     # 23 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://digitaltimestamp.clint.infocert.it/idts-rest/dts/welcome"
#     #   url_num      = 1
#     #   label        = "IDTS Welcome Service"
#     #   service_name = "IDTS-REST welcome"
#     #   product      = "IDTS"
#     #   tech_serv    = "ST Marcatura Temporale"
#     #   script       = "nav_GENERAL_pattern.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 10
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 24 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ecercl.infocert.it/ecer-webservice/"
#     #   url_num      = 1
#     #   label        = "Welcome Service"
#     #   service_name = "Hello World!"
#     #   product      = "ECER"
#     #   tech_serv    = "ST Generazione Altri Certificati"
#     #   script       = "nav_GENERAL_pattern.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 25 = {
#     #   enabled      = false //local.common.enabled
#     #   url          = "https://martecl.infocert.it/cdie/wtest.html"
#     #   url_num      = 1
#     #   label        = "Marcatura"
#     #   service_name = ""
#     #   product      = "MARTE"
#     #   tech_serv    = "ST Marcatura Temporale"
#     #   script       = "nav_MARTE_marcatura_selenium4.tpl"
#     #   user         = "MARTE_MARC_USER_CLD"
#     #   pass         = "MARTE_MARC_PASS_CLD"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   duration_thr = 4000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 26 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://marte.clint.infocert.it/cdie/wtest.html"
#     #   url_num      = 1
#     #   label        = "Marcatura Clint"
#     #   service_name = ""
#     #   product      = "MARTE"
#     #   tech_serv    = "ST Marcatura Temporale"
#     #   script       = "nav_MARTE_marcatura_selenium4.tpl"
#     #   user         = "MARTE_MARC_USER_CLD"
#     #   pass         = "MARTE_MARC_PASS_CLD"
#     #   freq         = 10
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 4000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 27 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://martecl.zucchetti.infocert.it/cdie/wtest.html"
#     #   url_num      = 1
#     #   label        = "Marcatura Zucchetti"
#     #   service_name = ""
#     #   product      = "MARTE"
#     #   tech_serv    = "ST TSA Zucchetti"
#     #   script       = "nav_MARTE_marcatura_selenium4.tpl"
#     #   user         = "MARTE_ZUC_MARC_USER_CLD"
#     #   pass         = "MARTE_ZUC_MARC_PASS_CLD"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   duration_thr = 4000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 29 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://mysigncl.infocert.it/#/login"
#     #   url_num      = 1
#     #   label        = "Login MySign CL"
#     #   service_name = "MySignCL"
#     #   product      = "MySign"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   script       = "nav_MYSIGN_login_new.tpl"
#     #   user         = "MYSIGN_LOGIN_USER_CLD"
#     #   pass         = "MYSIGN_LOGIN_PASS_CLD"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   duration_thr = 15000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 30 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://supernova.clint.infocert.it/login?redirect=%2Fhome"
#     #   url_num      = 1
#     #   label        = "Login Supernova"
#     #   service_name = "ma233699"
#     #   product      = "SUPERNOVA"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   script       = "nav_SUPERNOVA_templates_selenium4.tpl"
#     #   user         = "SUPERNOVA_LOGIN_USER_CLD"
#     #   pass         = "SUPERNOVA_LOGIN_PASS_CLD"
#     #   freq         = 10
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 6000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#   }

#   API_checks_info = {
#     # 1 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://pulsarcl.eu-west-1.claws.infocert.it/cl_regaut2/bind"
#     #   url_num      = 1
#     #   label        = "Bind"
#     #   service_name = ""
#     #   product      = "PULSAR"
#     #   tech_serv    = "ST Registration Authority 2"
#     #   script       = "PULSAR_Bind.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   priv_loc     = true
#     #   multi_loc    = false
#     #   duration_thr = 5000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#   }

#   checks_info_once_day = {
#     # 1 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://ip1cvliasblc001.clint.infocert.it:8081/api/probe/lei-job/last-execution"
#     #   url_num      = 1
#     #   label        = "LEI"
#     #   service_name = "LEI"
#     #   product      = "LCER JOB"
#     #   tech_serv    = "LCER JOB"
#     #   script       = "nav_JOB_scriptedAPI.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 1440
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 2 = {
#     #   enabled      = false
#     #   url          = "http://ip1cvliasblc001.clint.infocert.it:8081/api/probe/icss-expired-job/last-execution"
#     #   url_num      = 1
#     #   label        = "ICSS EXPIRED"
#     #   service_name = "ICSS EXPIRED"
#     #   product      = "LCER JOB"
#     #   tech_serv    = "LCER JOB"
#     #   script       = "nav_JOB_scriptedAPI.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 1440
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 3 = {
#     #   enabled      = false
#     #   url          = "http://ip1cvliasblc001.clint.infocert.it:8081/api/probe/trissq-expired-job/last-execution"
#     #   url_num      = 1
#     #   label        = "TRISSQ EXPIRED"
#     #   service_name = "TRISSQ EXPIRED"
#     #   product      = "LCER JOB"
#     #   tech_serv    = "LCER JOB"
#     #   script       = "nav_JOB_scriptedAPI.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 1440
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 4 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://ip1cvliasblc001.clint.infocert.it:8081/api/probe/notify-db-job/last-execution"
#     #   url_num      = 1
#     #   label        = "NOTIFY DB"
#     #   service_name = "NOTIFY DB"
#     #   product      = "LCER JOB"
#     #   tech_serv    = "LCER JOB"
#     #   script       = "nav_JOB_scriptedAPI.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 1440
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 5 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://ip1cvliasblc001.clint.infocert.it:8081/api/probe/log-pkbox-job/last-execution"
#     #   url_num      = 1
#     #   label        = "LOG PKBOX"
#     #   service_name = "LOG PKBOX"
#     #   product      = "LCER JOB"
#     #   tech_serv    = "LCER JOB"
#     #   script       = "nav_JOB_scriptedAPI.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 1440
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 6 = {
#     #   enabled      = local.common.enabled
#     #   url          = "http://ip1cvliasblc001.clint.infocert.it:8081/api/probe/renewal-job/last-execution"
#     #   url_num      = 1
#     #   label        = "RENEWAL"
#     #   service_name = "RENEWAL"
#     #   product      = "LCER JOB"
#     #   tech_serv    = "LCER JOB"
#     #   script       = "nav_JOB_scriptedAPI.tpl"
#     #   user         = ""
#     #   pass         = ""
#     #   freq         = 1440
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#   }

#   ping_monitors = {
#     # 1 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcarcl.infocert.it/CustomerCertEmitterWS/emitterCertRequest.wsdl"
#     #   url_num      = 1
#     #   label        = "CustomerCertEmitterWS"
#     #   service_name = "EmitterCertRequestService"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 2 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcarcl.infocert.it/infora-webservice/RegistrationBaseAut?wsdl"
#     #   url_num      = 1
#     #   label        = "RegistrationBaseAut"
#     #   service_name = "RegistrationBaseAutService"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 3 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcarcl.infocert.it/infora-webservice/RegistrationHandleWS?wsdl"
#     #   url_num      = 1
#     #   label        = "RegistrationHandleWS"
#     #   service_name = "RegistrationHandleWSService"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 4 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcarcl.infocert.it/infora-webservice/RegistrationWS?wsdl"
#     #   url_num      = 1
#     #   label        = "RegistrationWS"
#     #   service_name = "RegistrationWSService"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 5 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcarcl.infocert.it/AttCertFirma/WsAccContratti?wsdl"
#     #   url_num      = 1
#     #   label        = "WsAccContratti"
#     #   service_name = "WsAccContratti"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 6 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcarcl.infocert.it/AttCertFirma/WsAttCerts?wsdl"
#     #   url_num      = 1
#     #   label        = "WsAttCerts"
#     #   service_name = "WsAttivazioneCerts"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 7 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcarcl.infocert.it/AttCertFirma/WsVerXML?wsdl"
#     #   url_num      = 1
#     #   label        = "WsVerXML"
#     #   service_name = "WsVerificaXML"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 8 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://wcarcl.infocert.it/ERCWebService/ERCNServiceWS?wsdl"
#     #   url_num      = 1
#     #   label        = "ERCNServiceWS"
#     #   service_name = "ERCServiceFRService"
#     #   product      = "WCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # } 
#     # 9 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfrcl.infocert.it/ncfr-webservice/FirmaFR?wsdl"
#     #   url_num      = 1
#     #   label        = "FirmaFR"
#     #   service_name = "FirmaFR"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # } 
#     # 10 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfrcl.infocert.it/ncfr-webservice/FirmaWS?wsdl"
#     #   url_num      = 1
#     #   label        = "FirmaWS"
#     #   service_name = "firmaWSService"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 11 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfrcl.infocert.it/ncfr-webservice/GenCertFR?wsdl"
#     #   url_num      = 1
#     #   label        = "GenCertFR"
#     #   service_name = "GenCertFR"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 12 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfrcl.infocert.it/ncfr-webservice/GenCertMedWS?wsdl"
#     #   url_num      = 1
#     #   label        = "GenCertMedWS"
#     #   service_name = "GenCertMedService"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 13 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfrcl.infocert.it/ncfr-webservice/RegCertFR?wsdl"
#     #   url_num      = 1
#     #   label        = "RegCertFR"
#     #   service_name = "RegCertFR"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 14 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfrcl.infocert.it/ncfr-webservice/ManagerCredWS?wsdl"
#     #   url_num      = 1
#     #   label        = "ManagerCredWS"
#     #   service_name = "ManagerCredWSService"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 15 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfrcl.infocert.it/ncfr-webservice/RegCertMedWS?wsdl"
#     #   url_num      = 1
#     #   label        = "RegCertMedWS"
#     #   service_name = "RegCertMed"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 16 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfrcl.infocert.it/ncfr-webservice/OTPSender?wsdl"
#     #   url_num      = 1
#     #   label        = "OTPSender"
#     #   service_name = "OTPSenderWSService"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 17 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfrcl.infocert.it/ncfr-webservice/PKBoxManager?wsdl"
#     #   url_num      = 1
#     #   label        = "PKBoxManager"
#     #   service_name = "GenerateCertificatePKBoxService"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 18 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncfrcl.infocert.it/ncfr-webservice/ServerMaRe?wsdl"
#     #   url_num      = 1
#     #   label        = "ServerMaRe"
#     #   service_name = "ServerMaRe"
#     #   product      = "NCFR"
#     #   tech_serv    = "ST Firma Remota Intesi"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 19 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://digitaltimestamp.clint.infocert.it/idts-rest/dts/welcome"
#     #   url_num      = 1
#     #   label        = "IDTS Welcome Service"
#     #   service_name = "IDTS-REST welcome"
#     #   product      = "IDTS"
#     #   tech_serv    = "ST Marcatura Temporale"
#     #   freq         = 10
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
#     # 20 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://restcl.legalcert.infocert.it/lcrs-service/welcome/"
#     #   url_num      = 1
#     #   label        = "Welcome Service"
#     #   service_name = "Benvenuti in LCRS"
#     #   product      = "LCRS"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1500
#     #   max_failures = 0
#     # }
# 	  # 21 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncarcl.infocert.it/regws/services/RegistrazioneAnagraficaWS?wsdl"
#     #   url_num      = 1
#     #   label        = "RegistrazioneAnagraficaWS"
#     #   service_name = "DORegistrazioneAnagraficaService"
#     #   product      = "NCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
# 	  # 22 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://ncarcl.infocert.it/pcarweb/default.do"
#     #   url_num      = 1
#     #   label        = "Prenotazione Registrazione"
#     #   service_name = "Prenotazione richiesta registrazione"
#     #   product      = "NCAR"
#     #   tech_serv    = "ST Registration Authority"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 23 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://apistage.infocert.digital/validation/signature/v2/info"
#     #   url_num      = 1
#     #   label        = "Health Check v2 - claws"
#     #   service_name = "lcert-sigval-vaga"
#     #   product      = "VAGA"
#     #   tech_serv    = "sigval"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 24 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://apistage.infocert.digital/validation/signature/v3/info"
#     #   url_num      = 1
#     #   label        = "Health Check v3 - claws"
#     #   service_name = "lcert-sigval-vaga"
#     #   product      = "VAGA"
#     #   tech_serv    = "sigval"
#     #   freq         = 10
#     #   multi_loc    = true
#     #   priv_loc     = false
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 2
#     # }
#     # 25 = {
#     #   enabled      = local.common.enabled
#     #   url          = "https://atumcl.eu-south-1.clawsbc.infocert.it/atum/health"
#     #   url_num      = 1
#     #   label        = "Health Check - claws"
#     #   service_name = "\"status\": \"UP\","
#     #   product      = "ATUM"
#     #   tech_serv    = "ST-ATUM"
#     #   freq         = 10
#     #   multi_loc    = false
#     #   priv_loc     = true
#     #   priv_loc_ca  = false
#     #   duration_thr = 2000
#     #   result_thr   = 1200
#     #   max_failures = 0
#     # }
#   }
# }